version: "3.9"
networks:
  mynetwork:
  ipam:
    driver: bridge 

volumes: 
  prometheus_data: {}

services:
  web:
    image: flaskweb 
    
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  model: 
    image: model
    
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    depends_on:
      - web
  node-exporter:    
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:      
      - /proc:/host/proc:ro      
      - /sys:/host/sys:ro      
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'      
      - '--path.rootfs=/rootfs'      
      - '--path.sysfs=/host/sys'      
      - '--collector.filesystem.mount-points-exclude=\         
          ^/(sys|proc|dev|host|etc)($$|/)'
    expose:      
      - 9100    
    ports:       
      - 9100:9100 
    networks:      
      - mynetwork
  
  prometheus:     
    image: prom/prometheus:latest     
    container_name: prometheus     
    restart: unless-stopped
    volumes:       
      - C:/Users/Moise/Documents/Machine Learning in Production/project/prometheus:/prometheus/prometheus.yml
      - C:/Users/Moise/Documents/Machine Learning in Production/project/prometheus_data:/prometheus_data
    command:      
      - '--config.file=/etc/prometheus/prometheus.yml'      
      - '--storage.tsdb.path=/prometheus_data'      
      - '--web.console.libraries=/etc/prometheus/console_libraries'      
      - '--web.console.templates=/etc/prometheus/consoles'      
      - '--web.enable-lifecycle'
    ports:       
      - 9090:9090
    expose:      
      - 9090
    networks:       
      - mynetwork


#volumes:
#  myvolume:
#    #driver: local
