version: "3.9"
networks:
  mynetwork:
  ipam:
    driver: bridge 

volumes: 
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  
  
  

services:
  web:
    image: flaskweb 
    
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    

  model: 
    image: model
    
    ports:
      - "5001:5001"
    
    volumes: 
      - ./modeldata:/app/data
    networks:
      - mynetwork
    depends_on:
      - web
  node-exporter:    
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:      
      - /proc:/host/proc:ro      
      - /sys:/host/sys:ro      
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'      
      - '--path.rootfs=/rootfs'      
      - '--path.sysfs=/host/sys'      
      - '--collector.filesystem.mount-points-exclude=\         
          ^/(sys|proc|dev|host|etc)($$|/)'
    expose:      
      - 9100    
    ports:       
      - 9100:9100 
    networks:      
      - mynetwork
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    # user: "501"
    # environment:
    # - PUID=501 
    # - PGTD=501
    privileged: true
    volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
       - ./prometheus-data:/prometheus
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'  
     
    ports:       
      - 9090:9090
    expose:      
      - 9090
    networks:       
      - mynetwork
  
  
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    # user: "501"
    ports:
      - "3030:3000"
    volumes:
      - ./grafana_data/data:/var/lib/grafana
      - ./grafana_data/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana_data/provisioning:/etc/grafana/provisioning
      # - ./grafana/data: /var/lib/grafana
    # user: "1000" 
    depends_on:
      - prometheus
    
    networks:       
      - mynetwork
    restart: unless-stopped

  


#volumes:
#  myvolume:
#    #driver: local
