global:  
  scrape_interval: 15s

scrape_configs:  


  - job_name: 'web'
  
    scrape_interval: 15s
    static_configs:      
      - targets: ['project-web-1:5000']
    

  - job_name: 'model'
    
    scrape_interval: 15s
    static_configs:      
      - targets: ['project-model-1:5001']

  - job_name: 'node-exporter'
    
    scrape_interval: 15s
    static_configs:      
      - targets: ['node-exporter:9100']

  

 