global:  
  scrape_interval: 5s

scrape_configs:  
  - job_name: 'web'
    scrape_interval: 5s
    static_configs:      
    - targets: ['web:5000']
    
scrape_configs:  
  - job_name: 'model'
    scrape_interval: 5s
    static_configs:      
    - targets: ['model:5001']